services:

  app:
    build: .
    container_name: usa_visa_predictor_app   
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      - mlflow


  mlflow:
    build:
      context: ./mlflow
    container_name: mlflow_server
    ports:
      - "5050:5000"
    volumes:
      - mlflow_data:/mlruns
      - mlflow_data:/mlartifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  mlflow_data:
