services:

  app:
    build: .
    container_name: usa_visa_predictor_app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      - db
      - mlflow


  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  mlflow:
    build:
      context: ./mlflow
    container_name: mlflow_server
    ports:
      - "5050:5000"
    volumes:
      - mlflow_data:/mlruns
      - mlflow_data:/mlartifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:
  mlflow_data:
