name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start Docker containers
        run: |
          docker compose -f compose.yaml build
          docker compose -f compose.yaml up -d
          # Optional: Add a delay to ensure services are up and ready
          sleep 10
          docker compose -f compose.yaml ps

      - name: Run DVC commands in Docker container
        run: |
          docker compose -f compose.yaml run app dvc pull
          docker compose -f compose.yaml run app dvc repro

      - name: Push Docker Image to DockerHub
        run: |
          docker tag us_visa_predictor-app:latest ${{ secrets.DOCKER_USERNAME }}/usa_visa_predictor-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/usa_visa_predictor-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/usa_visa_predictor-app:latest

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/usa_visa_predictor-app:latest
